### ISSUE TITLE
After stopping a video it always restarts 

### ISSUE THREAD

**Issue by piedrok** [flaviotordini/minitube#94]
This is on arch linux with the latest gnome and fully up to date system. 

Everytime I stop a minitube video the UI shows me the minitube page of my subscriptions and restarts the sound of the last video in the background. Changing to another subscribed channel doesn't stop the video from running and it even shows in the player area after clicking on a thumbnail in the left panel to choose another video. 

The only way to stop the same video from playing over and over again is to choose a video from the thumbnail panel and then click the restart video button of the player. After that changing the video within the channel works. 

I tried to catch some useful output by starting minitube from console but it doesn't give any console output while running. 

Minitube 2.9

**Comment by aproposnix** [comment]
I'm having this issue as well on Ubuntu 18.04 Daily. On my 16.04 Machines, I do not have this issue.

**Comment by JoR-Coder** [comment]
Also on Arch, but with debug turned on.
Since I do not know what could help Flavio finding out what is failing here, I'll just dump some stuff and hope he'll clarify stuff.

I get a bunch of these...
[unknown] CachedHttp MISS "https://i.ytimg.com/vi/FsCbmxTA7Gs/mqdefault.jpg"

[unknown] Cannot get token. Trying next el param "errordetail=0&errorcode=150&status=fail&reason=This+video+contains+content+from+TV4.+It+is+restricted+from+playback+on+certain+sites+or+applications.%0A%3Ca+href%3D%27http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DDbbCAFxNo6Q%26feature%3Dplayer_embedded%27+target%3D%27_blank%27%3EWatch+on+YouTube%3C%2Fa%3E" "&token=([^&]+)"

(But I do get token later...
[unknown] Got token and urlMap 1 "1")

When minitube starts plaing, a bunch of stuff gets dumped and...
[unknown] Success! 10679

And when stopping...
Lot's of
[unknown] Deleting "***********"
And it starts playing the stopped video, and dumping...
[unknown] Success! 10680

No errormessages etc.

**Comment by piedrok** [comment]
It would be nice to get a comment on his issue... 

It still happens everytime and it doesn't matter whether I tell minitube to use "manuell start video" or to stop after finishing a video... 

Sadly this makes browsing between videos very inconvenient - basically the workaround is after finishing a video to close minitube and restart it and navigate to another video.... 

Any help? Any ideas?

**Comment by piedrok** [comment]
This says I closed it. 

Well, sure not intentionally because nothing change until now... 

Now it's gnome 3.30.1 on Arch fully updated... 

How can I reopen this issue again - the problem is really very disturbing: It's seems like with every clikc on a video title it's added to a list instead of being played. 

I have no idea how to trouble shoot or what to do. 

Please can we get a comment on the problem?

**Comment by emilward85** [comment]
It is now December 4th, 2018, a year since this issue was originally opened and I also am having this issue. I'm on Pop_OS 18.04

**Comment by flaviotordini** [comment]
I'm planning to port away from Phonon so this bug will surely be fixed for the next release.

**Comment by flaviotordini** [comment]
This is fixed now on git
